#!/bin/bash

echo "================================================"
echo "  MANUALNI START - ROOT PROCES BLOKIRA PORT"
echo "================================================"
echo ""
echo "Root proces drži port 3001."
echo ""
echo "URADI SLEDEĆE:"
echo ""
echo "1. Ubij root proces:"
echo "   sudo kill -9 42452"
echo ""
echo "2. Pokreni server:"
echo "   cd /home/noname/Desktop/drone_radio_tokivoki_all-freq-scann-locator"
echo "   NODE_ENV=production node server.js"
echo ""
echo "ILI jednostavno:"
echo ""
echo "   sudo kill -9 \$(sudo lsof -ti tcp:3001) && NODE_ENV=production node server.js"
echo ""
echo "================================================"
